melange-re/melange

jscomp/bsb/bsb_ninja_file_groups.ml
- make `.cmi` depend on their dependencies correctly
- we were previously doing this for `.cmj` files, this change applies the same arguments to the `.cmi` module builds
Unfortunately writing interfaces is not that common in the ReScript world, which made this bug stay hidden for longer than I would have liked.
cc @jchavarri
=> Track cmi dependencies correctly

README.md
Start out with 2 questions that people have already asked a few times.
=> Start a FAQ section in the README

README.md
[rendered](https://github.com/anmonteiro/bucklescript/blob/anmonteiro/readme-context/README.md)
=> README: Add context around how this project relates to other tools

jscomp/bsb/bsb_ninja_gen.ml, jscomp/bsb/bsb_ninja_rule.ml
Found while building https://github.com/reazen/relude/pull/293
=> emit relative dev includes

esy.json, esy.lock/index.json, esy.lock/opam/dune-build-info.2.8.4/opam, esy.lock/opam/ppx_yojson_conv_lib.v0.14.0/opam, esy.lock/opam/reason.3.7.0/opam
I think this should be the preferred version to use currently?
=> use @opam/reason

jscomp/bsb_helper/bsb_helper_depfile_gen.ml
- For dependencies that live in the same directory, we first group them by their common directory, and then construct a glob that matches all those files
This brings the perf gains on a relatively large project to 38% from baseline, in conjunction with #100.
=> Group globs in bsb_helper

jscomp/ext/literals.ml, jscomp/main/bsb_main.ml
=> Generate dune-project with action-plugin 0.1 if it does not exist

jscomp/bsb/dune, jscomp/ext/dune, jscomp/others/dune.gen, jscomp/test/dune.gen, scripts/ninja.js
they're not used right now, but we'll need them for a playground bundle, for example.
=> pass cppo flags from env to more targets

jscomp/core/bs_conditional_initial.ml, nix/default.nix
Let's look for `lib/melange` in the installation dir.
=> Fix the build after stdlib include

jscomp/bsb/bsb_ninja_file_groups.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb/bsb_ninja_rule.mli
This fixes https://github.com/rescript-lang/rescript-compiler/issues/4184 (previous PR candidate: https://github.com/rescript-lang/rescript-compiler/pull/4349)
=> Run the JSX PPX in OCaml files too

.gitignore, jscomp/bsb_helper/bsb_helper_depfile_gen.ml, jscomp/common/js_config.cppo.ml, jscomp/core/bs_conditional_initial.ml, jscomp/ext/ext_list.ml, jscomp/ext/ext_list.mli, jscomp/main/bsb_main.ml, jscomp/main/js_main.ml, jscomp/stdlib-412/stdlib_modules/dune.gen, nix/sources.nix, scripts/ninja.js
This diff is better read commit by commit.
Just moving a function around, fixing a few dependency issues, and a bug around `bsc --where` and include directories in dev.
=> Fix stdlib_path bugs, small refactor

jscomp/stdlib-412/stdlib_modules/dune.gen, nix/ci/test.nix, scripts/ninja.js
=> Fix dune.gen generation, and add a CI check

jscomp/frontend/ppx_entry.ml, jscomp/main/js_main.ml, jscomp/napkin/dune
Unwraps napkin lib. Part of https://github.com/melange-re/melange/issues/113
=> Unwrap napkin lib

CONTRIBUTING.md
@anmonteiro I wanted to get this PR up so we could get some 👀 on it. I think I covered the very basics, but I'm happy to collect feedback and add more.
=> Add Nix setup instructions to CONTRIBUTING.md

jscomp/main/cmjdump_main.ml, jscomp/test/class3_test.js, jscomp/test/class4_test.js, jscomp/test/class5_test.js, jscomp/test/class6_test.js, jscomp/test/class7_test.js, jscomp/test/class8_test.js, jscomp/test/class_fib_open_recursion_test.js, jscomp/test/class_repr.js, jscomp/test/class_test.js, jscomp/test/gpr_1285_test.js, jscomp/test/gpr_2250_test.js, jscomp/test/if_used_test.js, jscomp/test/js_obj_test.js, jscomp/test/js_string_test.js, jscomp/test/large_obj_test.js, jscomp/test/obj_curry_test.js, jscomp/test/obj_test.js, jscomp/test/opr_3576_test.js, jscomp/test/opr_4560_test.js, jscomp/test/test_simple_obj.js, nix/sources.nix
Some of the recently cherry-picked commits (1afa65438ce91d5b26553815bfceae827aab3135, a06036ad218b181e3b084e4bbb94430b5fafc3f9) caused generated JS output to differ, and I forgot to commit the diff before.
=> Snapshot a few test files

.github/workflows/esy-build.yml, jscomp/ext/ext_path.ml, jscomp/ounit_tests/ounit_path_tests.ml, jscomp/ounit_tests/ounit_scc_tests.ml, jscomp/ounit_tests/ounit_union_find_tests.ml
there are still 5 remaining failures that I haven't bothered to look into. An adventure for another time
=> Fix a few windows tests

flake.lock, flake.nix, jscomp/core/lam_convert.ml, jscomp/core/lam_print.ml, jscomp/test/dune.gen, jscomp/test/mel_267_test.js, jscomp/test/mel_267_test.ml, nix/ci/test.nix
=> Fix s |> obj##prop after 4.14 upgrade

jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb_helper/bsb_helper_depfile_gen.ml, jscomp/bsb_helper/bsb_helper_depfile_gen.mli, jscomp/main/dune, jscomp/main/meldep.ml
I believe this to be the last CLI that we distribute with the Melange distribution to be converted to cmdliner.
=> Convert meldep to cmdliner

CONTRIBUTING.md
Updates information about how to get up and running with nix
=> docs: Update contributing section about nix

jscomp/bsb/bsb_ninja_rule.ml
fixes https://github.com/melange-re/melange/issues/317
=> Add `bsc-flags` to `.cmj`  / `.js` rules too

Makefile, flake.lock, ppx_rescript_compat/ppx_rescript_compat.ml
fixes #329 
/cc @eWert-Online
there might still be other AST nodes lurking that I need to add. Feedback appreciated.
=> ppx_rescript_compat: handle Pexp_apply too

flake.lock, jscomp/core/lam_compile_main.ml, jscomp/main/melc.ml, jscomp/main/melc_cli.ml
Fixes https://github.com/melange-re/melange/issues/347
=> Add `-alert`

jscomp/bsb/bsb_build_util.ml, jscomp/bsb/bsb_build_util.mli, jscomp/bsb/bsb_config_parse.ml, jscomp/bsb/bsb_exception.ml, jscomp/bsb/bsb_global_paths.ml, jscomp/bsb/bsb_global_paths.mli, jscomp/bsb/bsb_merlin_gen.ml, jscomp/bsb/bsb_ninja_rule.ml, jscomp/bsb/bsb_unix.ml, jscomp/bsb/mel_workspace.ml, jscomp/bsb/mel_workspace.mli, jscomp/bsb_helper/bsb_helper_depfile_gen.ml, jscomp/bsb_helper/bsb_helper_depfile_gen.mli, jscomp/main/mel.ml, jscomp/main/melc.ml, jscomp/main/meldep.ml
=> use relative paths in meldep

flake.lock, ocaml-tree/package.json, shell.nix
fixes https://github.com/melange-re/melange/issues/176
=> Set up `"engines"` field in the `ocaml-tree` package.json

melange.opam, melange.opam.template
The right path was the one before, see https://github.com/melange-re/melange/pull/364#discussion_r1000505557.
=> fix melangelib path in opam

.github/workflows/esy-build.yml, .github/workflows/nix-build.yml, .github/workflows/opam-build.yml, dune-project, melange.opam
~Blocked until Dune 3.5 is released.~
Adds a new workflow in CI to test opam.
=> ci: add opam

.github/workflows/opam-build.yml
There's a new repo https://github.com/melange-re/melange-opam-template.
=> ci: use melange-opam-template

.github/workflows/opam-build.yml, jscomp/core/dune, nix/shell.nix, ocaml-tree/package.json
Found the fix in https://github.com/grahambates/m68k-lsp/issues/6.
=> Support node 18

dune-project, esy.json, nix/default.nix, test/dune, test/simple.t
=> Add first cram test case

flake.lock, jscomp/main/mel.ml, jscomp/main/mel_watcher.ml, jscomp/main/mel_watcher.mli
=> [mel]: fix watcher exiting after the first change

README.md
=> `ocaml-lsp` should be renamed to `ocaml-lsp-server`

README.md
Add a minimal setup for Neovim LSP builtin.
=> editor support: add neovim

jscomp/core/js_name_of_module_id.ml, jscomp/core/js_packages_info.ml, jscomp/core/js_packages_info.mli, jscomp/core/lam_compile_main.ml, jscomp/ext/dune, jscomp/ext/ext_js_file_kind.mli, jscomp/ext/ext_namespace.ml, jscomp/ounit_tests/ounit_string_tests.ml
- move `module_case` to `Js_packages_info`
- Rename `Little` to `Lowercase`
=> refactor: module case

.github/workflows/esy-build.yml, .github/workflows/nix-build.yml, .github/workflows/opam-build.yml
uses the same fix I applied in https://github.com/nix-ocaml/nix-overlays/pull/562
=> test(ci): cancel previous CI runs

jscomp/core/js_name_of_module_id.ml, test/belt-and-runtime.t
`commonjs` works fine, but there seems to be some issue with `es6`.
=> add test for belt and runtime

.github/workflows/esy-build.yml, Makefile, flake.lock, flake.nix, jscomp/test/dune, nix/ci/test.nix, test/dune-js-file-unmangling.t/dune, test/shadow-internal-lib.t/dune, test/shadow-internal-module.t/dune
- https://github.com/ocaml/dune/pull/7302
=> fix: adapt to latest dune changes

test/melange-ppx-private.t
=> Add test for doc comment attached to `%%private`

.github/workflows/opam-build.yml, flake.lock, nix/ci/test.nix, nix/default.nix, nix/overlay.nix, nix/shell.nix
start assuming 3.8 now that it's been tagged
=> chore: update flakes and overlay

jscomp/core/lam_compile_main.mli, jscomp/others/belt.ml, jscomp/others/belt_internalAVLtree.ml, jscomp/others/js_cast.mli, jscomp/others/js_json.mli, jscomp/others/js_re.ml, jscomp/others/js_string.ml, jscomp/others/js_string2.ml
=> docs: replace refs to rescript

CONTRIBUTING.md
Seems nix is already configured, but have to do manual work on opam.
=> contributing: update to mention submodules

dune-project, melange.opam
as was caught in https://github.com/ocaml/opam-repository/pull/23907
=> chore: add ppxlib lower bound

.github/workflows/nix-build.yml, .github/workflows/opam-build.yml, Changes.md, bin/jsoo_main.ml, bin/melc.ml, dune-project, flake.lock, flake.nix, jscomp/core/ast_io.ml, jscomp/core/js_implementation.ml, jscomp/core/lam_convert.ml, jscomp/core/polyvar_pattern_match.ml, jscomp/core/res_compmisc.ml, melange.opam, nix/ci/test.nix, test/blackbox-tests/dune, test/blackbox-tests/intoverflow.t, test/blackbox-tests/lam-convert-exn.t, test/blackbox-tests/legacy-ounit-cmd.t, test/blackbox-tests/mel-attributes.t
- Depends on https://github.com/melange-re/melange-compiler-libs/pull/19
- Stdlib coming in a subsequent PR
=> feat: Upgrade compiler to OCaml 5.1

flake.lock, test/blackbox-tests/uncurry-errors.t
fixes https://github.com/melange-re/melange/issues/682
=> Fix: uncurried application error messages

.github/workflows/opam-build.yml, Makefile
Needs #692 before being merged.
The tests were removed in #619 for some reason.
=> [playground] add back tests to ci

jscomp/runtime/caml_bytes.ml, jscomp/runtime/caml_bytes.mli
=> fix: add missing Caml_bytes.set{32,64}u

Changes.md, flake.lock, test/blackbox-tests/print-attrs-error.t
Fixes #747.
Fixes #806.
Companion PR: https://github.com/melange-re/melange-compiler-libs/pull/30.
The first commit shows current behavior in `main`. Second one shows the diff after picking the changes from that ^  compiler libs PR.
=> Cleanup attrs errors

bin/melc_cli.ml, jscomp/others/dune, jscomp/runtime/dune, jscomp/stdlib/dune, jscomp/test/dist-es6/jscomp/test/mt.mjs, jscomp/test/dist/jscomp/test/mt.js, jscomp/test/dune, jscomp/test/mt.ml, jscomp/test/re_or_res/recursive_react_component.re, test/unit-tests/dune, test/unit-tests/ounit_bal_tree_tests.ml, test/unit-tests/ounit_unicode_tests.ml
- `-bs-no-version-header` only affects emission, so it only works on `melange.emit`
- fix a few warnings in test files
=> fix: remove `-bs-no-version-header` from some dune files, fix warnings

jscomp/core/js_config.cppo.ml, jscomp/ext/ext_path.ml, jscomp/ext/ext_path.mli
viewed best without whitespace https://github.com/melange-re/melange/pull/831/files?w=1
=> refactor: remove / replace functions in Ext_path

Changes.md
motivated by https://github.com/melange-re/melange/pull/796#discussion_r1378625875
=> fix(changelog): mention that removing Belt is breaking

flake.lock, jscomp/common/lam_constant.ml, jscomp/common/lam_constant.mli, jscomp/common/lam_tag_info.mli, jscomp/core/lam_compile_primitive.ml, jscomp/core/lam_constant_convert.ml, jscomp/core/lam_convert.ml
necessary for #742, extracted from #884
=> feat: propagate constructor attributes from the typechecker

Changes.md, jscomp/runtime/js.ml, jscomp/test/dist/jscomp/test/flow_parser_reg_test.js, jscomp/test/dist/jscomp/test/js_obj_test.js, jscomp/test/dist/jscomp/test/ocaml_parsetree_test.js, jscomp/test/dist/jscomp/test/ocaml_typedtree_test.js, jscomp/test/js_obj_test.ml
fixes https://github.com/melange-re/melange/issues/795
=> feat: add `Js.Obj.merge`

ppx/melange_ppx.ml
fixes https://github.com/melange-re/melange/issues/741
=> fix(ppx): list alerts that can be turned off in command line arguments

jscomp/others/belt_HashMap.mli, jscomp/others/belt_HashSet.mli, jscomp/others/belt_Map.mli, jscomp/runtime/js.ml, jscomp/runtime/js_internal.ml
follow-up to https://github.com/melange-re/melange/pull/701
=> fix(doc): more odoc warnings

Changes.md, jscomp/core/ast_payload.ml, ppx/ast_attributes.ml, ppx/ast_attributes.mli, ppx/ast_core_type_class_type.ml, ppx/ast_core_type_class_type.mli, ppx/ast_derive/ast_derive_abstract.ml, ppx/ast_derive/ast_derive_projector.ml, ppx/ast_derive/ast_derive_util.ml, ppx/ast_derive/ast_derive_util.mli, ppx/ast_exp_apply.ml, ppx/ast_extensions.ml, ppx/ast_external_process.ml, ppx/ast_mel_open.ml, ppx/ast_payload.ml, ppx/ast_payload.mli, ppx/ast_tuple_pattern_flatten.ml, ppx/ast_util.ml, ppx/error.ml, ppx/error.mli, ppx/melange_ppx.ml, test/blackbox-tests/melange-ppx-raw.t, test/blackbox-tests/ppx-errors.t
follow-up to https://github.com/melange-re/melange/pull/928 and https://github.com/melange-re/melange/pull/924
=> fix(ppx): better error messages in `melange.ppx`

flake.lock
https://github.com/ocaml/dune/releases/tag/3.12.0
=> chore: update flakes to get Dune 3.12

jscomp/common/external_ffi_types.ml, jscomp/common/external_ffi_types.mli, jscomp/core/mel_ast_invariant.ml, ppx/ast_exp_apply.ml, test/blackbox-tests/unprocessed-attributes.t
fixes the suggestion made in https://github.com/melange-re/melange/issues/633#issuecomment-1822843403
=> feat(ppx): print an `unprocessed` alert on Melange's infix ops

jscomp/stdlib/bytesLabels.mli, jscomp/stdlib/dune
=> fix: update the signature for ByteLabels to match upstream

ppx/melange_ppx.ml, ppx/utf8_string.ml, ppx/utf8_string.mli, test/unit-tests/ounit_unicode_tests.ml
found while investigating https://github.com/melange-re/melange/pull/863
=> refactor(ppx): clean up utf8_string

ppx/ast_external_process.ml, ppx/ast_external_process.mli
this function already exists in `Ast_external_mk`
=> ppx: remove unused, duplicated function

.github/workflows/nix-build.yml
ocaml seems to fail to compile everytime
=> ci: disable arm64 mac

Changes.md, bin/melc.ml, bin/melc_cli.ml, flake.lock, jscomp/core/js_dump_program.ml, jscomp/core/js_name_of_module_id.ml, jscomp/melstd/module_system.ml, jscomp/melstd/module_system.mli, playground/mel_playground.ml
part of https://github.com/melange-re/melange/issues/1066
=> melange: start parsing "esm" and "esm-global" for module system too

Changes.md, flake.lock, jscomp/core/compile_rec_module.cppo.ml, jscomp/core/initialization.cppo.ml, jscomp/melstd/ident0.ml, jscomp/melstd/ident0.mli, jscomp/melstd/js_pp.ml, jscomp/melstd/mel_ident.mli, jscomp/runtime/caml_module.ml, test/blackbox-tests/rec-module.t
=> fix: recursive modules in the presence of mangled idents

jscomp/core/dune, jscomp/core/gen/gen_traversal.ml, jscomp/melstd/dune, jscomp/melstd/gen/build_reserved.ml
=> fix(windows): don't write binary on stdout

.github/workflows/nix-build.yml
issues we were seeing in #1085 have been fixed
=> ci: re-enable arm64 runner

Changes.md, jscomp/core/initialization.cppo.ml, jscomp/core/melc_warnings.ml, jscomp/core/melc_warnings.mli, test/blackbox-tests/unprocessed-attributes.t
=> feat: make the `unprocessed` alert fatal

jscomp/runtime/js_array.ml
=> runtime(Js.Array): port `@mel.send` externals to use `@mel.this`

jscomp/runtime/js_float.ml, jscomp/runtime/js_int.ml
ports #1272 and #1273 to #1285
=> runtime(Js.{Int,Float}): port `@mel.send` externals to use `@mel.this`

Changes.md, jscomp/core/lam_convert.cppo.ml, test/blackbox-tests/syntactic-function-arity.t
fixes #1253 for default arguments
=> fix: missed optimization in function argument fusion with default args

Changes.md, dune, jscomp/core/dune
=> fix: melange build on profiles other than dev/release

Changes.md, jscomp/runtime/js_writableStream.ml
=> add `Js.WritableStream`

jscomp/test/arity_ml.ml, jscomp/test/dune, jscomp/test/external_ppx.ml, ppx/ast_attributes.ml, ppx/ast_attributes.mli, ppx/ast_typ_uncurry.ml, test/blackbox-tests/uncurry-nested-fn.t
=> fix: account for new warning 34 instances

jscomp/melstd/io.ml, jscomp/melstd/io.mli, jscomp/melstd/melstd.ml
Lifts the optimizations done in dune for file reading
=> melstd: add `Melstd.Io` with faster file reading
