melange-re/melange

- jscomp/syntax/ast_reason_pp.ml
- nix/sources.nix
somewhat unbelivably, BuckleScript made a change
(https://github.com/rescript-lang/rescript-compiler/commit/1d5c782ed)
around the time we landed the re-error diff that resulted in swallowing
_all_ Reason syntax errors and returning a generic syntax error instead.
> Don't swallow Reason parsing errors

- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_rule.ml
- generate `(subdir` rules with a relative directory, otherwise dune segfaults
- add missing `(action (run` to the rule that builds the NS package
Ideally we avoid generating the `lib/bs` directory altogether, and especially the namespace stuff there. That will enable out of source builds.
> Fix namespaces

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_file_groups.mli
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_targets.ml
- jscomp/bsb/bsb_ninja_targets.mli
fixes #23 
- we were emitting rules for the `bs-dev-dependencies`, but not depending on them in the dev source dirs.
> Fix bs-dev-dependencies

- jscomp/bsb/bsb_build_util.ml
- jscomp/ext/ext_filename.ml
- jscomp/ext/ext_filename.mli
Dune interprets `'` (single-quote) characters as part of a segment, so
we need to use `"` (double-quote) in the generated dune files
cc @jchavarri
> Fix shell quoting for dune

- jscomp/ext/ext_ident.ml
This is the 2nd part of #23 (thanks @TheSpyder!).
The bug was easily reproduced with:
```ocaml
external describe : string -> unit = "describe" [@@bs.val ]
let describe = describe
```
Before this fix, the generated code looked like:
```js
function describe(prim) {
describe(prim);
}
exports.describe = describe;
```
After the fix:
```js
function describe$1(prim) {
describe(prim);
}
exports.describe = describe$1;
```
> Fix a codegen bug related to `Ident.t` and recursion

- jscomp/bsb/bsb_global_paths.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_targets.ml
- jscomp/main/dune
- jscomp/others/dune.gen
- jscomp/runtime/dune.gen
- jscomp/stdlib-412/dune.gen
- jscomp/stdlib-412/stdlib_modules/dune.gen
- jscomp/test/dune.gen
- scripts/ninja.js
This does the changes needed to be able to build the project itself on Windows.
The `.exe` suffix was removed as it's not needed and it breaks dune on Windows. So the binaries are now `bsc`, `bsb`, `bspack`, `bsb_helper`, `bsb_parse_depend`
When the stdlib needed quotes it was adding quotes two times, one when making the global_config and the other one when including the files
- #34
> Fix CI on Windows, builds bsc and bsb

- jscomp/core/lam_exit_count.ml
- jscomp/core/lam_exit_count.mli
- jscomp/core/lam_pass_exits.ml
When getting the runtime tests to run, one of the more puzzling failures was one related to inlining of expressions within `match ... with | exception ...`.
- The test correspods to https://github.com/ocsigen/js_of_ocaml/issues/400
- In upstream OCaml, it was tracked in https://github.com/ocaml/ocaml/issues/7680, and fixed in https://github.com/ocaml/ocaml/pull/1497
This patch is an attempt at an almost direct port of the aforementioned PR to OCaml to work within this codebase.
> Fix incorrect inlining of match .. with | exception .. in non-tail position

- jscomp/core/lam_analysis.ml
- jscomp/core/lam_dispatch_primitive.ml
- jscomp/runtime/caml_sys.ml
- jscomp/runtime/caml_sys.mli
- jscomp/stdlib-412/stdlib.mli
- jscomp/stdlib-412/stdlib_modules/camlinternalLazy.ml
- jscomp/stdlib-412/stdlib_modules/camlinternalLazy.mli
- jscomp/stdlib-412/stdlib_modules/camlinternalOO.ml
- jscomp/stdlib-412/stdlib_modules/hashtbl.ml
- jscomp/stdlib-412/stdlib_modules/lazy.ml
- jscomp/stdlib-412/stdlib_modules/obj.ml
- jscomp/stdlib-412/stdlib_modules/obj.mli
- jscomp/stdlib-412/stdlib_modules/pervasives.ml
- jscomp/stdlib-412/stdlib_modules/printexc.ml
- jscomp/stdlib-412/stdlib_modules/stdlib__no_aliases.ml
- jscomp/stdlib-412/stdlib_modules/sys.ml
- jscomp/stdlib-412/stdlib_modules/sys.mli
Fixes the runtime for the following features / modules
- `Sys`
- refs
- `Lazy`
- OCaml classes
- `Hashtbl`
- `Printexc`
> Fix runtime for: lazy, Printexc, refs, obj, hashtbl

- jscomp/bsb/bsb_world.ml
- jscomp/bsb/bsb_world.mli
- jscomp/main/bsb_main.ml
The previous behavior of generating a dune file containing rules for
only the toplevel project is not a good default if `bsb` is now
effectively just a frontend to dune.
fixes #40
> Only generate the `dune.bsb` file if `-make-world` is passed

- jscomp/frontend/ast_tdcls.ml
- jscomp/test/bs_abstract_test.ml
The code generated by `bs.deriving abstract` makes the target type abstract. It achieves that by generating code that looks e.g. like the following:
```ocaml
include (struct
type t = {
x: string
}
end : sig  end)
type t
```
The warning is correct in the sense that the type effectively becomes unused. OCaml 4.12 started detecting cases like this, so the fix is to just turn it off for the original type.
- Turned on `warn-error` for warning 34 in the existing test for `bs.deriving abstract` and verified:
- test fails to compile before this fix
- test compiles fine after the fix
fixes #28 
cc @thespyder
> Don't issue warning 34 (unused type) for `bs.deriving abstract`

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_targets.ml
There are two changes in the PR:
1. 72d7054 stops calling `Filename.basename` in the rule generation by default
2. 67900f6 is the real fix. it makes sure to not mess with the path that the user wrote in `bsconfig.json`
- in the future we should probably assert that this is a relative path, though dune might take care of that for us now.
bug reported by @jchavarri
> Generators: don't call basename on inputs

- README.md
- jscomp/bsb/bsb_clean.ml
- jscomp/bsb/bsb_clean.mli
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb_helper/bsb_db_decode.ml
- jscomp/bsb_helper/dune
- jscomp/ext/dune
- jscomp/main/bsb_main.ml
- jscomp/main/dune
- jscomp/main/js_main.ml
- jscomp/runtime/dune.gen
- jscomp/stdlib-412/dune.gen
- jscomp/stdlib-412/stdlib_modules/dune.gen
- jscomp/test/dune.gen
- scripts/ninja.js
- Divided into 3 commits:
- d52e7d0 Generate the project's rules when we get `-install` at the CLI (this fixes #15)
- d0864b0 unifies `-clean` and `-clean-world`, so they do the same
- b84f89d this last one just cleans up some warnings throughout the codebase; some minor refactoring
> Generate dune files with `-install`, unify `-clean` and `clean-world`, clean up some warnings

- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_gen.ml
- directories that don't have targets were still generating an empty alias, which dune doesn't seem to like
The error was exposed to the user as:
```
Error: No rule found for alias
node_modules/rescript-apollo-client/src/@apollo/client/errors/__tests__/bsb_world
```
Reported by @jfrolich
> Don't add a dependency on directories without targets

- jscomp/frontend/ast_external_process.ml
- jscomp/test/dune.gen
- jscomp/test/external_intf_impl.js
- jscomp/test/external_intf_impl.ml
- jscomp/test/external_intf_impl.mli
In e.g. a `[@bs.obj] external ...` context, assuming too much can lead to type errors. Here's an example:
```ocaml
(* x.mli *)
external x :
?primary:bool -> unit -> < primary: bool option   >  Js.t = ""[@@bs.obj ]
(* x.ml *)
external makeProps :
?primary:'primary -> unit -> < primary: 'primary option   >  Js.t = ""[@@bs.obj]
```
In this case, the type-directed optimization assumed different types and caused a type mismatch.
> Don't assume some types can be unnested just by the impl type

- .github/workflows/esy-build.yml
This use our new self-hosted Mac Mini M1 as a way to ensure bucklescript is running on macOS ARM64
This solution is temporary, while https://github.com/actions/virtual-environments/issues/2187 is not solved
> ci: add macOS ARM64

- jscomp/napkin/res_ast_conversion.ml
- jscomp/napkin/res_core.ml
- jscomp/napkin/res_printer.ml
- Revert the rest of https://github.com/rescript-lang/syntax/pull/291
- we had previously reverted the JSX PPX portions, but it's important to revert the rest of the PR too, for folks that want to keep using ReScript syntax with this project.
> napkin: revert the rest of upstream PR#291

- jscomp/ext/ext_path.ml
- a code path in this function was wrong for cases where paths might be like `foo/./bar`. In these cases, we can't append a `../` segment.
> Fix `Ext_path.rel_normalized_absolute_path` to handle `.` segments in all cases

- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_config.ml
- jscomp/bsb/bsb_config.mli
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.ml
- jscomp/bsb/bsb_merlin_gen.ml
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_global_vars.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/main/bsb_main.ml
- Previously we were including an absolute path to a "guessed" install directory
- This relied on guessing that the dune build directory would be `_build/default`
- If we instead relativize the include paths then we don't have to care about where dune stores build artifacts at all
- unfortunately we still need to know where artifacts are going to end up in order to generate the dune file
- I also refactored this code path to read `DUNE_BUILD_DIR` from the environment, if present.
> Relativize include dirs

- jscomp/napkin/reactjs_jsx_ppx_v3.ml
- jscomp/test/dune.gen
- jscomp/test/reactjs_ppx_custom.js
- jscomp/test/reactjs_ppx_custom.re
- After https://github.com/reasonml/reason/pull/2541, Longidents are now being properly passed
- The React JSX PPX was relying on the previous, odd behavior, which appended `createElement` at the end of a long identifier.
This change relaxes the constraint that JSX calls need to end with `make` or `createElement`. The following case was affected:
```reason
module Internal = {
[@react.component]
let header = () => <div />;
};
[@react.component]
let make = () => <Internal.header />;
```
- Included a test case that failed to compile before this change.
> React JSX PPX: generalize calling expressions to all identifiers

- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_file_groups.ml
- jscomp/bsb/bsb_file_groups.mli
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_parse_sources.ml
- Dune ignores subdirectories that start with `_`
- `__tests__` is a common one that people have in their projects
- this change tells dune about subdirectories that should be included based on what gets passed to `subdirs: ...` in `bsconfig.json`
fixes #70
> Tell dune about directories starting with `_`

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/main/bsb_main.ml
- Right now it's assumed that the sourcedirs meta was generated in the first place. Therefore you have to run bsb with `bsb -install -make-world`. 
- I think we can always generate the `sourcedirs.json`, so I'll lift this restriction in a separate PR.
> If project has a gentype config, depend on sourcedirs.json meta

- jscomp/bsb/bsb_ninja_targets.ml
This one is straightforward:
- Add an `(enabled_if (= %{ocaml_version} "4.12.0+BS"))` stanza to every generated rule
This effectively makes `bsb` generated rules invisible to native projects.
fixes #64
> Make `bsb` generated rules available for the 4.12.0+BS version only

- jscomp/main/bsb_main.ml
we already default to generate the dune files in `-install`. default to
generating sourcedirs meta when `-install` is not passed.
This is the second part of https://github.com/melange-re/melange/pull/66
> Generate sourcedirs meta by default when `-make-world` is passed

- README.md
This adds the extra steps that might not be immediately obvious to someone unused to using `esy` as well as remove the ROADMAP that was still pointing to rescript repo, we can add our ROADMAP later whenever we're ready with one
> README: Remove legacy and improve usage guide

- jscomp/frontend/ast_attributes.ml
- jscomp/napkin/res_printer.ml
Given the compatibility with OCaml it is probably also good to just keep `bs.deriving`.
> only use @bs.deriving, because of collisions with `ppxlib`

- jscomp/bsb/bsb_config.mli
- jscomp/bsb/bsb_db_encode.ml
- jscomp/bsb/bsb_db_util.ml
- jscomp/bsb/bsb_db_util.mli
- jscomp/bsb/bsb_exception.ml
- jscomp/bsb/bsb_namespace_map_gen.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_global_vars.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_world.ml
- jscomp/bsb_helper/bsb_db_decode.ml
- jscomp/bsb_helper/bsb_db_decode.mli
- jscomp/bsb_helper/bsb_helper_depfile_gen.ml
- jscomp/ext/bsb_db.ml
- jscomp/ext/bsb_db.mli
- jscomp/ext/literals.ml
- jscomp/ext/map.cppo.ml
- jscomp/ext/map_gen.ml
- jscomp/ext/map_gen.mli
- jscomp/main/bsb_parse_depend.ml
- jscomp/ounit_tests/ounit_bsb_pkg_tests.ml
This change relaxes the restriction that implementation and interface files for the same module must live in the same directory.
- Dune's [virtual library](https://dune.readthedocs.io/en/stable/variants.html) support allows to compile parameterized libraries and defer the selection of a concrete implementation until linking.
- It works by declaring a library with "virtual modules" (where only interface files are present), usually in a different directory than the corresponding implementation files
- This change allows projects that share code between native and JS targets can now rely on these interface files (in another directory), and satisfy those interfaces with their JS specific implementations, by relaxing the restriction that implementation and interface files for the same module …
> Allow implementation and interface files to live in different dirs

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/main/bsb_parse_depend.ml
In order to track dynamic dependencies we were:
1. reading each `*.d` file produced by `bsb_helper`
2. for each dependency in the `*.d` file, track it in dune by reading
their file contents
We can avoid reading files into memory altogether by calling the
`read_directory_with_glob` function instead, which declares dependencies
on those files without reading their contents.
> Dune action-plugin: don't read unnecessary file contents

- jscomp/common/js_config.ml
- jscomp/common/js_config.mli
- jscomp/ext/ext_file_extensions.ml
- jscomp/frontend/ast_reason_pp.ml
- jscomp/frontend/ast_reason_pp.mli
- jscomp/main/js_main.ml
- Adds support for parsing / printing from / to all supported syntaxes in `bsc`
- caveat: res / reason don't interop so well. Right now comments aren't preserved when converting between these. It works OK for OCaml <-> Reason
- further work: if folks end up using this feature, we can write a res <-> reason comment converter in order to support comments from res <-> re
> Format from / to all supported syntaxes

- jscomp/bsb/bsb_parse_sources.ml
fixes #87 
For projects that want to check in generated code, set`cut-generators: false` in `bsconfig.json`
> Enable generators by default (even in dependencies)

- README.md
Because we don't use resolutions anymore there is no need to add resolutions, also ocaml-lsp for 4.12 was released.
This is finally starting to look like a nice workflow.
> docs: Update README to use new esy workflow

- jscomp/frontend/bs_ast_invariant.ml
For ocaml compatibility. It should now be safe to do after #59
> Remove ast invariants forbiding to redefine builtin types

- jscomp/core/js_implementation.ml
- jscomp/frontend/ast_derive.ml
- jscomp/frontend/ast_deriving_compat.ml
- jscomp/frontend/ast_deriving_compat.mli
This change implements @mathspy's suggestion from https://github.com/melange-re/melange/pull/93#issuecomment-809909358.
To avoid ppxlib failing when it doesn't recognize a Melange / ReScript deriver (e.g. `accessors`, `abstract`, `jsConverter`), we convert those from `[@"deriving" ...]` to `[@bs.deriving ...]` before applying the PPX pass.
This is a compatibility-focused fix for https://github.com/rescript-lang/rescript-compiler/issues/5036
> Compatibility with ppxlib derivers

- jscomp/bsb/bsb_parse_sources.ml
problematic case:
```json
"sources": [
{
"dir": "ends/with/slash/",
"subdirs": true
}
],
```
> Normalize paths that are compared

- jscomp/main/bsb_main.ml
Reproducing the comment I added:
> for the edge case of empty sources (either in user config or because a
source dir is empty), we emit an empty `bsb_world` alias. This avoids
showing the user an error when they haven't done anything.
> bsb: declare add an empty `bsb_world` alias to avoid hard failure

- .github/workflows/esy-build.yml
The fork of the esy action was adding `arch -arm64` on every esy call, this is not needed anymore as I recently moved the wrapper from the action to the CI machine itself as it is more reliable and the machine can then be shared with other repositories.
> simplify esy-build CI

- jscomp/bsb/bsb_ninja_file_groups.ml
If `"sources"` looks like:
```json
"sources": [
{
"dir": "src",
"subdirs": [ "a" ]
},
{
"dir": "src/pages",
}
]
```
we were effectively ignoring the `src/pages` directory. the `(dirs` stanza was added to fix #70 because Dune ignores directories starting with `_` by default, but including only the ones we know from `subdirs` is clearly not enough.
> specify :standard for dune dirs

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/ext/ext_path.ml
- jscomp/ounit_tests/ounit_path_tests.ml
This is the same bug that I fixed in #60, but in another branch of the same function.
I made sure to add tests for the fix in #60 and for the case we found today.
> Fix relative path calculation in the presence of `.`

- .github/workflows/esy-build.yml
- esy.json
- jscomp/ounit_tests/ounit_cmd_util.ml
Turns out that the tests already run on esy if we ignore-promoted-rules like the ones that uses `web-tree-sitter` this will works.
In the future we may use different mechanism so that ignore-promoted-rules will not be needed.
#126
> Run tests on CI with esy 

- jscomp/main/js_main.ml
Came across it as I was diffing the flags with ocamlc
> Remove duplicate flag (-nolabels)

- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_config.ml
- jscomp/bsb/bsb_config.mli
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.ml
- jscomp/bsb/bsb_merlin_gen.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_file_groups.mli
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_global_vars.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_ninja_rule.mli
- jscomp/bsb/bsb_ppxlib.ml
- jscomp/bsb/bsb_ppxlib.mli
- jscomp/main/bsb_main.ml
fixes #121 
- generates a ppxlib driver on the fly
> Allow using PPXes as libraries 

- jscomp/core/bs_conditional_initial.ml
- jscomp/core/res_compmisc.ml
fixes #173 
We need to add the stdlib include dir at the end of the includes so that it doesn't shadow modules with the same name in a project.
> Fix stdlib module shadowing

- jscomp/bsb/bsb_ninja_rule.ml
dune can track dependencies properly
> Don't pass `-bs-version` and ppx mtime to bsc

- CONTRIBUTING.md
Sometimes using NixOS is not straightforward, so adding these docs in case a contributor needs to build and run the project using just esy.
> Document build steps using just esy

- esy.json
- esy.lock/index.json
- esy.lock/opam/merlin.4.2-412/opam
- esy.lock/opam/ocaml-lsp-server.1.5.0/opam
As `ocaml-lsp-server` was already released for 4.12 we don't need to keep using it like this, and also some weird bugs was happening on the master version.
Something like `unit_of_yojson` then the LSP crashes, maybe @rgrinberg is interested on it?
> use ocaml-lsp-server from opam

- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_ninja_rule.mli
- jscomp/bsb/bsb_ninja_targets.ml
- jscomp/bsb/bsb_ninja_targets.mli
- jscomp/outcome_printer/dune
This makes that error messages uses reason when it's a reason file
```shell
File "/home/eduardo/reason/gh-feed-reader/_build/default/src/App.re", line 6, characters 11-23:
6 | type x = t(list(string), string);
^^^^^^^^^^^^
Error: This type list(string) should be an instance of type option('a)
```
As the hooks were already in place and this feature was possible in the past, I figured it out that it was actually just enabling it on dune.
It was partially broken because the migration to melange-compiler-libs tho.
Implements #166
> Use reason on error messages

- jscomp/core/lam_compile_main.ml
- nix/sources.nix
This allows commands using -impl / -intf with -o, to work normally, dune emits this kind of commands. Currently this only generates the `.cmj`
```sh
bsc -I . -o a_something.cmj -impl a.ml
```
Will generate both the `a_something.cmj` and `a_something.js`
> emit JS file when using -o with -impl

- esy.json
- jscomp/main/dune
Improve the development experience and enable easier debugging with ocamlearlybird.
- Enable (modes byte) for `js_main`
- Adds the needed stubs to run `js_main.bc` on the `esy.json`.
My current workflow is:
```sh
dune build jscomp/main/js_main.bc -w --ignore-promoted-rules
alias bsc="$cur__target_dir/default/jscomp/main/js_main.bc"
bsc -version
```
> enables bytecode mode on bsc for development

- jscomp/core/js_cmj_format.ml
- jscomp/core/js_cmj_format.mli
- jscomp/core/js_implementation.ml
- jscomp/core/js_implementation.mli
- jscomp/core/lam_compile_main.ml
- jscomp/core/lam_stats_export.ml
- jscomp/core/lam_stats_export.mli
- jscomp/ext/ext_file_extensions.ml
- jscomp/main/js_main.ml
This is a step on moving to support dune directly, by being able to generate JS from the cmj we achieve a flow quite similar to ocamlc + jsoo.
And this also aims to reduce duplicated work when the user has multiple targets, like CJS and ES6, which today runs the full pipeline twice.
ALSO, this allows to have relocatable builds even in the presence of absolute paths, because the stored program is not dependent on the path. And because JS is not platform dependent this is a safe operation.
The cmj file will be considerable now, while before it was a dumb and helped with optimizations, now it carry the full JS AST.
If this starts to be a problem there is a couple of ways to mitigate it.
- Add `J.deps_program` to the cmj
- Emits JS from the cmj
- Fix bug where `-o x/out.js -impl y/in` would …
> Store program in cmj and generates JS from it

- README.md
In https://github.com/melange-re/melange/commit/e3d84e4e0011955ae620331ba9d0876b41938451#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L17, Melange lost the content of the Acknowledgments section, and replaced it with only a link to [`Credits.md`](https://github.com/melange-re/melange/blob/a11ceb137489bb42c32cbe8c499220b5172060f5/Credits.md). This was a quite lossy change, as it lost:
- Explicit credit to the OCaml team.
- Credit to ninja (is Melange still using ninja internally?)
- Credit to Bloomberg and Facebook for supporting the BuckleScript project.
`Credits.md` does not have any of this. It is a list of sources for some of the components of ReScript (and Melange).
As far as I can tell, all of these should be acknowledged. In addition, the text [was already …
> README: restore Acknowledgments section

- jscomp/bsb/bsb_clean.ml
- jscomp/bsb/bsb_clean.mli
- jscomp/main/bsb_main.ml
- nix/sources.nix
- shell.nix
- When developing a project of mine inside a monorepo, I need to pass `--root=.` to `dune clean`
- This was planned but I never got around to implementing it
> Pass dune arguments (after `--`) to `dune clean`

- jscomp/bsb/bsb_merlin_gen.ml
- jscomp/common/js_config.cppo.ml
- jscomp/common/js_config.mli
- jscomp/core/bs_conditional_initial.ml
- jscomp/main/js_main.ml
- when running in non-release mode:
- print include directories
- add local development include dirs to the merlin file
> Developer experience improvements

- jscomp/bsb/bsb_ninja_targets.ml
Reverts melange-re/melange#234
We'll only want this when we require dune 3.0
> Revert "use `lib-available:melange` to guard melange stanzas"

- jscomp/bsb/bsb_ninja_targets.ml
- jscomp/bsb_helper/bsb_helper_depfile_gen.ml
Aligns with the final form of https://github.com/ocaml/dune/pull/5442 where the contents of the deps file needs to be a s-expression.
> dune file generation tweaks

- jscomp/core/lam_compile_external_call.ml
- jscomp/frontend/ast_external_process.ml
- jscomp/frontend/external_ffi_types.ml
- jscomp/frontend/external_ffi_types.mli
- jscomp/runtime/caml_splice_call.ml
- jscomp/runtime/caml_splice_call.mli
- jscomp/test/splice_test.js
- jscomp/test/splice_test.ml
This PR allows `@new` and `@variadic` to be used simultaneously.
```js
'use strict';
class Foo {
constructor(...names) {
this.names = names;
}
}
let foo = new Foo("bar", "baz");
console.log(foo.names);
```
```rescript
type foo
@get external names: foo => array<string> = "names"
@new @variadic external makeFoo : array<string> => foo = "Foo"
let foo = makeFoo(["bar", "baz"])
Js.log(foo->names)
```
> Support @new @variadic

- flake.lock
- jscomp/core/dune
- jscomp/core/js_implementation.ml
- jscomp/core/js_implementation.mli
- jscomp/main/melc.ml
- nix/default.nix
- ppx_rescript_compat/dune
- ppx_rescript_compat/ppx_rescript_compat.ml
- ppx_rescript_compat/ppx_rescript_compat.mli
This PR introduces a ReScript compatibility layer that aims to run on ReScript files and translate some of the Melange-incompatible transforms to compatible AST nodes.
This allows applications that use ReScript features to work within Melange codebases.
Right now, the only transform the PPX performs is `obj["prop"]` -> `obj##prop`.
> Introduce a ReScript compatibility layer

- flake.lock
- jscomp/common/js_config.cppo.ml
- jscomp/others/dune.gen
- jscomp/runtime/dune.gen
- jscomp/stdlib-412/stdlib_modules/dune.gen
- jscomp/test/dune.gen
- scripts/ninja.js
- in `.merlin`, emit a real path, rather than a symlink + relative path 
- generate `.cmt` and `.cmti` build artifacts in the melange codebase
> Fixes for dev-time Merlin

- flake.lock
- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_clean.ml
- jscomp/bsb/bsb_config.ml
- jscomp/bsb/bsb_config.mli
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.mli
- jscomp/bsb/bsb_db_encode.ml
- jscomp/bsb/bsb_merlin_gen.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_global_vars.ml
- jscomp/bsb/bsb_ninja_regen.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_package_specs.ml
- jscomp/bsb/bsb_world.ml
- jscomp/bsb/dune
- jscomp/build_tests/monorepo/bsconfig.json
- Remove the `bs-external-includes` option, but emit a warning saying it's not supported
- because we use dune, there are better ways of supporting external includes
- Clean up the `Bsb_config` module, we need way less stuff here
> `mel` cleanup

- jscomp/ext/ext_path.ml
- jscomp/ext/ext_path.mli
- jscomp/ext/ext_string.cppo.mli
- jscomp/ounit_tests/ounit_path_tests.ml
- jscomp/ounit_tests/ounit_string_tests.ml
- shell.nix
Notably, if the result of `Ext_path.concat "foo" "./bar"` is `"foo/./bar"`, that can't be passed to `mkdirp`
> Fix a few bugs in `Ext_path.concat`

- .gitignore
- nix/default.nix
- shell.nix
This makes `nix run github:melange-re:melange` just work, e.g.:
```shell
$ nix run github:melange-re/melange -- build 
```
> Add meta.mainProgram

- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_pkg.ml
- jscomp/bsb/bsb_pkg.mli
In reference to issue #300
This unifies the resolution of packages under a single `resolve_package` function.
It'd probably be a good idea to simply remove the `bsb_path_resolver` module and put all its functionality under `bsb_pkg` instead.
> refactor: unify usage of resolve_package functions

- jscomp/bsb/bsb_build_util.ml
- jscomp/bsb/bsb_build_util.mli
- jscomp/bsb/bsb_config.ml
- jscomp/bsb/bsb_config.mli
- jscomp/bsb/bsb_config_parse.ml
- jscomp/bsb/bsb_config_types.mli
- jscomp/bsb/bsb_exception.ml
- jscomp/bsb/bsb_merlin_gen.ml
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_file_groups.mli
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_ninja_targets.ml
- jscomp/bsb/bsb_package_specs.ml
- jscomp/bsb/bsb_package_specs.mli
- jscomp/bsb/bsb_pkg.ml
- jscomp/bsb/bsb_world.ml
- jscomp/bsb_helper/bsb_helper_depfile_gen.ml
- jscomp/bsb_helper/bsb_helper_depfile_gen.mli
- jscomp/main/meldep.ml
Tools like [Yarn PnP](https://yarnpkg.com/features/pnp) and the [`NODE_PATH` environment variable](https://nodejs.org/api/modules.html#loading-from-the-global-folders) enable module resolution outside of the workspace (in contrast with the familar `node_modules` folder in the root directory).
Melange used to generate some build artifacts in-source before #296. That produces an error if those directories are read-only (in e.g. Nix, they are).
After #296 and #302, we no longer write any artifacts to dependency directories, and only write the `dune.mel` file in the workspace directory.
- Not writing any artifacts to the dependency directories is the first step
- However, Dune will refuse to build anything outside the workspace
- This PR creates a "virtual filesystem" within Dune rules (using …
> Enable fully out of source builds

- README.md
This solves the 'invalid syntax' highlight, comments are invalid JSON but valid JSONC
> Switch readme examples to jsonc

- jscomp/bsb/bsb_warning.ml
Commit 3926929d6b37e010474a90643d48ffdfbb651d9e removed pinned dependencies.
It broke bsconfig warning configuration handling, all the warning codes
were parsed but not included into the dune rule generation.
Fixed the issue by bringing back the original warning handling excluding
the pinning dependencies part.
**Behavior before**
Code
```
type test = A | B | C;
let test = C;
let result =
switch (test) {
| A => "A"
| B => "B"
};
```
bsconfig.json
```
"warnings": {
"number" : "+8",
"error" : "+8"
}
```
Generated dune.mel
```
(run melc  -w a -bs-jsx 3  -absname -bs-ast -o %{targets} %{inputs}))
```
No warnings or errors were reported because `-w a` disables all the warnings on top level.
**Behavior after the fix**
```
(run melc -w +8 -warn-error +8 -bs-jsx 3  -absname -bs-ast -o %{targets} …
```
> Generate warning parameters based on bsconfig

- README.md
[`ocaml-lsp-server 1.12.0`](https://github.com/ocaml/ocaml-lsp/releases/tag/1.12.0) includes the commit that adds the `--fallback-read-dot-merlin` flag, so we no longer need to use an unreleased version.
Related: melange-re/melange-basic-template#16
> Update editor instructions to use released version of ocaml-lsp-server

- jscomp/main/melc.ml
- jscomp/main/melc_cli.ml
Given a `bsconfig.json` like [the following](https://github.com/ELLIOTTCABLE/excmd.js/blob/3cb1ef3bd8c41a3505776f57209588ae96955ea6/packages/bs-excmd/bsconfig.json#L85-L94),
```json5
"package-specs": [
{
"module": "es6",
"in-source": true
},
{
"module": "commonjs",
"in-source": false
}
],
```
A bug is currently producing:
```
melc: option '--bs-package-output' cannot be repeated
```
This PR fixes that by iterating over all `--bs-package-output` flags.
([Discord ref](https://discord.com/channels/235176658175262720/825155604641218580/1015008383646044180).)
> Allow multiple --bs-package-output options

- jscomp/bsb/bsb_db_encode.ml
To prevent "Argument list too long" errors for very large projects. This error happens due to `execve` used by dune hitting ARG_MAX (or MAX_ARG_STRLEN, not sure) limit.
Initially tried creating tmp file using `mktemp` but it's more intrusive approach, that also would break on windows.
Also tried using EOT/EOF but this would not fix the issue.
In the end, the simplest fix seems to be to split the string in smaller chunks and use `progn` to concatenate all `echo` runs.
> Split bsbuild serialized cache in chunks

- jscomp/main/melc.ml
- jscomp/main/melc_cli.ml
This flag is used by dune to avoid generating additional `.cmi` files when `.mli` files are present, see 
- `Module_compilation` [in dune](https://github.com/ocaml/dune/blob/5736b997bfe18e6d03a389b0416ff541bda79c51/src/dune_rules/module_compilation.ml#L4-L10)
- and `Compenv` in [ocaml trunk](https://github.com/ocaml/ocaml/blob/949e2626c22b5fe8159cb29d47207d5621eabf90/driver/compenv.ml#L408)
> Add -intf-suffix

- jscomp/main/melc.ml
- jscomp/main/melc_cli.ml
Sorry to not have added this in #338.
Having these flags makes dune integration easier, but we can discuss if all of them are needed. E.g. does `g` make sense under melange context?
> Add more ocamlc flags

- jscomp/main/melc.ml
Fixes #336.
Any processing done when passing `-impl` or `intf` flags is wrapped inside `try` statement, to reuse `Location.report_exception` for those cases too.
> Try/catch errors when passing -impl and -intf flags

- jscomp/main/melc.ml
Quick repro:
```
cat > test.mli <<EOL
val t : string
EOL
```
In `fork`:
- calling ` melc -bin-annot -o test.cmi -c -intf test.mli` will not generate `test.cmti`
- calling `melc -bs-no-bin-annot -o test.cmi -c -intf test.mli` will generate `test.cmti`
This patch fixes it, so each action does the opposite from `fork`, while preserving default behavior (generate `cmti` when neither `-bin-annot` or `-bs-no-bin-annot` are passed).
> Fix -bin-annot and -bs-no-bin-annot handling

- jscomp/bsb/bsb_world.ml
- jscomp/main/mel.ml
Respect the `"generate-merlin"` configuration flag
> Run merlin generation conditionally

- ppx_rescript_compat/ppx_rescript_compat.ml
fixes https://github.com/melange-re/melange/issues/335
> Fix ReScript compat for `foo["bar"](arg1, arg2)`

- jscomp/core/lam_convert.ml
- jscomp/test/ocaml_typedtree_test.js
For sourcemaps my plan is to add back Levent on melange-compiler-libs and remove it on Lam_convert, making so that we have the locations data available on Melange.
But if we do that, a bunch of pattern matching that were not expecting Levent now don't happen.
Always convert first to Lam.t and then match, this was mostly already implemented but here I finish the patch.
**warning** this change the order of some transformations, which matters because we use mutation in a couple places, so the artifact that changed looks reasonable to me.
But I didn't fully test it, ideally we could test it in some big projects.
> lam: convert first then match, helps when Levent

- dune.mel
- jscomp/bsb/bsb_db_encode.ml
- jscomp/bsb/bsb_db_encode.mli
- jscomp/bsb/bsb_namespace_map_gen.ml
- jscomp/bsb/bsb_namespace_map_gen.mli
- jscomp/bsb/bsb_ninja_file_groups.ml
- jscomp/bsb/bsb_ninja_file_groups.mli
- jscomp/bsb/bsb_ninja_gen.ml
- jscomp/bsb/bsb_ninja_gen.mli
- jscomp/bsb/bsb_ninja_rule.ml
- jscomp/bsb/bsb_ninja_rule.mli
- jscomp/bsb/bsb_ninja_targets.ml
- jscomp/bsb/bsb_ninja_targets.mli
- jscomp/bsb/bsb_ppxlib.ml
- jscomp/bsb/bsb_ppxlib.mli
- jscomp/bsb/bsb_world.ml
- jscomp/bsb/bsb_world.mli
- jscomp/main/mel.ml
Avoids buffering the entire contents of `dune.mel` in memory
> dune.mel: use an Out_channel.t instead of a Buffer.t

- jscomp/frontend/bs_builtin_ppx.ml
- jscomp/test/gh_161.js
- jscomp/test/gh_161.res
- jscomp/test/gh_161_ml.js
- jscomp/test/gh_161_ml.ml
- jscomp/test/ocaml_typedtree_test.js
- ppx_rescript_compat/ppx_rescript_compat.ml
**breaking change**
Melange inherited from ReScript a transformation that changes `let` with a pattern matching in records to `match`. This improves some common cases of type inference in OCaml, but is actually a breaking change.
This happens because let does type checking of the pattern then the value, while match does the opposite, and in OCaml this matters.
The following code shows the difference in behavior between `bsc` and `ocamlc`.
```ocaml
module X = struct
type t = { id: int }
end
(* fails in ocamlc *)
let builds_in_melange =
let { id = id } = X.{ id = 0 } in
id
(* builds in ocamlc *)
let fails_in_melange =
let { X.id = id } = { id = 0 } in
id
```
Thanks @Octachron for pointing this out to me.
> revert patch that transforms let into match

- CONTRIBUTING.md
- Makefile
- Adds some commands in `Makefile` to set up local switch
- Update contributing docs
We can remove manual install of `ocaml-lsp-server` once opam 2.2.0 is out, which will include a `--with-dev-setup` [flag](https://github.com/ocaml/opam/pull/5214).
> Opam dev flow

- .github/workflows/opam-build.yml
- `opam pin add . --with-test` should take care of building in release mode and running the melange tests
> fix(ci): speed up opam build

- jscomp/core/lam_compile_main.ml
- jscomp/stubs/bs_hash_stubs.cppo.ml
- jscomp/stubs/ext_basic_hash_stubs.c
Revert "add runtime support"
This reverts commit 47cdb1eb1af8c501d6fe005b37b0402e77fb3a61.
Companion to https://github.com/melange-re/melange-compiler-libs/pull/4
> Revert warning hacks (pulled from upstream)

- .github/workflows/opam-build.yml
- We removed the reason dependency for melange 0.3 in #409 
- the opam tests rely on it
> fix(opam-tests): install reason in OPAM tests

- jscomp/core/bs_conditional_initial.ml
- jscomp/frontend/bs_ast_invariant.ml
- jscomp/frontend/ppx_entry.ml
- Part of the work to make the compiler agnostic to syntaxes
- counterpart to https://github.com/melange-re/melange-compiler-libs/pull/6
> [melc]: remove references to `Config.syntax_kind`

- jscomp/frontend/ast_tdcls.ml
- test/unused-record-fields.t
@anmonteiro I ran into this issue and thought on sharing it in case it can be fixed on Melange side.
As Melange in Dune is using [OCaml byte default flags](https://github.com/ocaml/dune/blob/9fb391c8ac0c2608481a62cb603de6d4bc95407b/src/dune_rules/module_compilation.ml#L167-L169), and warning 69 [was introduced in 4.13.0](https://github.com/ocaml/ocaml/pull/10232), these warnings that did not happen with ReScript are raised now on Melange.
Maybe the warning could be silenced at Melange ppx level? In `bs.optional` attrs?
> bs.optional + bs.deriving abstract shows warning 69

- Changes.md
- jscomp/napkin/ppx_rescript_compat/ppx_rescript_compat.ml
- jscomp/test/rescript_compat.js
- jscomp/test/rescript_compat.res
fixes https://github.com/melange-re/melange/issues/439
> fix(ppx_rescript_compat): fix conversion to `##`

- Changes.md
- dune.mel
- flake.lock
- flake.nix
- jscomp/core/bs_conditional_initial.ml
- jscomp/core/js_implementation.ml
- jscomp/main/melc.ml
- jscomp/main/melc_cli.ml
- mel/bsb_ninja_file_groups.ml
- mel/mel_rule.ml
- mel/mel_rule.mli
- fixes https://github.com/melange-re/melange/issues/368
- pre-requisite: https://github.com/melange-re/melange-compiler-libs/pull/10
> [mel]: remove `-bs-read-cmi` and lean on `-intf-suffix`

- jscomp/core/js_implementation.ml
- nix/default.nix
- test/intf-suffix.t
I was assuming `melc` was rewriting `cmi` files when generating `cmj`s, but it does not seem to be the case.
Opening a PR in case the test is useful or can be improved to be so.
> test intf-suffix invariant

- Changes.md
- flake.lock
- flake.nix
- jscomp/core/lam_compile_main.ml
- jscomp/main/melc.ml
- test/no-package-name-in-js-objs.t
- test/no-package-name-in-js.t
before:
```shell
$ melc --pp 'refmt --print=binary' -impl x.re
melc: internal error, uncaught exception:
File "jscomp/core/lam_compile_main.ml", line 315, characters 19-25: Assertion failed
```
after:
```shell
$ melc -pp 'refmt --print=binary' -impl x.re
melc: no output specified (use -o <filename>.js)
```
fixes #465
> melc: actionable error message when no output is specified with `-impl`

- .github/workflows/opam-build.yml
- Makefile
- dune-project
- melange.opam
- Consolidates installation of test/dev dependencies between Makefile and ci scripts
- Makes sure tests run in ci on the opam pipeline
> ci: run tests in opam pipeline

- Changes.md
- jscomp/core/res_compmisc.ml
- test/stack-module.t
Something changed recently (since Feb 20) that breaks unwrapped libraries and it becomes impossible to define modules that overlap with those in stdlib.
> add test with stack module

- jscomp/frontend/bs_builtin_ppx.ml
- test/melange-ppx-uncurry.t
Demonstrate a strange issue with `bs` attr and warning 101.
> test: demonstrate issue with `bs` attr and warning 101

- .github/workflows/opam-build.yml
- Makefile
`opam pin add melange --with-test` already runs the tests.
> test: don't run tests twice for the opam flow

- Makefile
After adding rescript-syntax package, which includes `melange {= version}` dep, opam chokes a bit because it tries to find some version of melange but can't:
```
<><> Installing new switch packages <><><><><><><><><><><><><><><><><><><><><><>
Switch invariant: ["ocaml-base-compiler" {= "4.14.1"} | "ocaml-system" {= "4.14.1"}]
[ERROR] Could not determine which packages to install for this switch:
* Missing dependency:
- melange < 0.2.0
no matching version
```
Adding `--no-install` fixes the problem.
Some `.dev` suffices to dune and compiler libs pins for consistency, and a small fix on `opam-init` are included as well.
> makefile: fix opam-create-switch

- Changes.md
- flake.lock
- jscomp/main/dune
- jscomp/main/melc.ml
- jscomp/main/melpp.ml
- we've noticed that it's a bit hard to understand when the melange ppx runs and how it interacts with ocamldep
- the biggest reason for running `melc --as-pp` so far has been to resolve the `#if` conditional processing in the melange modified parser
- in this change we introduce a dedicated `melpp` executable that _just_ parses the input file and outputs AST on stdout
> melange: Add a `melpp` executable that just preprocesses conditionals

- .github/workflows/esy-build.yml
- .github/workflows/nix-build.yml
- .github/workflows/opam-build.yml
- .gitmodules
- Makefile
- dune-project
- flake.lock
- flake.nix
- jscomp/ast_derive/dune
- jscomp/ast_extensions/dune
- jscomp/astlib/dune
- jscomp/common/dune
- jscomp/core/dune
- jscomp/ext/dune
- jscomp/frontend/dune
- jscomp/main/dune
- jscomp/ounit_tests/dune
- melange.opam
- nix/ci/test.nix
- nix/default.nix
- nix/overlay.nix
- rescript-syntax/dune
- vendor/dune
- Vendors https://github.com/melange-re/melange-compiler-libs
- converts some libraries back to private libraries
The main advantage of this change is that we can stop releasing the internal `melange-compiler-libs` package to opam.
We'll still maintain the repository and the git history over there to preserve authorship and keep it easy to merge with upstream OCaml. Otherwise all the melange internal libraries are considered internal, and keeping them as dune private libraries enforces that.
> chore: vendor melange-compiler-libs

- jscomp/ext/ext_string.cppo.mli
- jscomp/others/belt_Array.mli
- jscomp/others/belt_List.mli
- jscomp/others/belt_Map.mli
- jscomp/others/belt_MapDict.mli
- jscomp/others/belt_Option.mli
- jscomp/others/belt_Result.mli
- jscomp/others/belt_Set.mli
- jscomp/others/belt_SortArray.mli
- jscomp/others/js_dict.mli
- jscomp/others/js_exn.mli
- jscomp/others/js_float.ml
- jscomp/others/js_global.ml
- jscomp/others/js_int.ml
- jscomp/others/js_json.mli
- jscomp/others/js_null.mli
- jscomp/others/js_null_undefined.mli
- jscomp/others/js_obj.ml
- jscomp/others/js_re.ml
- jscomp/others/js_string.ml
- jscomp/others/js_string2.ml
- jscomp/others/js_types.mli
- jscomp/others/js_undefined.mli
- jscomp/others/map.cppo.mli
- jscomp/runtime/js.ml
I noticed several sample snippets in code comments were using the `@example` directive, but I could not find anything about it on the [odoc documentation](https://ocaml.github.io/odoc/odoc_for_authors.html#tags). They only [mention](https://ocaml.github.io/odoc/odoc_for_authors.html#ocaml_code_blocks) regular `{[]}` blocks.
It's also rendered mostly as a string, as seen in the image below, which is weird.
This PR removes them.
> docs: remove example tags

- .gitignore
I added some vscode config after the vendoring of compiler-libs, so that vscode only tracks the main melange repository:
```json
{
"git.ignoredRepositories": ["vendor/melange-compiler-libs"]
}
```
As this kind of setting choice might vary between contributors, i think the best is to ignore `.vscode` folder altogether.
> gitignore vscode folder

- jscomp/frontend/melange_ppx.ml
- test/melange-ppx-raw.t
Melange ppx throws when passing a function callback as payload of the `%raw` attribute.
> melange ppx: fatal error when parsing %raw with callback

- Changes.md
- jscomp/main/dune
In https://github.com/ocaml/opam-repository/pull/23850#issuecomment-1571343049, @smorimoto mentioned some bytecode-only platforms were missing executables in the package installation.
This change allows those platforms to build too.
> chore: use default dune modes for executables

- jscomp/core/js_name_of_module_id.ml
- jscomp/core/js_packages_info.ml
- jscomp/core/js_packages_info.mli
- jscomp/core/js_packages_state.ml
- jscomp/ext/literals.ml
melange's runtime / stdlib is now built with dune, which consolidates all the logic for finding the runtime modules too.
> refactor: clean up legacy runtime logic

- dune-project
- melange.opam
Continuation of #617 (which was not fixing anything really).
Fixes some issues in opam-repository lower bounds ci checks, by picking the `menhir` constraint that was part of `melange-compiler-libs` and bringing it over to `melange`. cc @davesnx
> melange.opam: add lower bound for menhir

- bin/dune
- bin/jsoo_common.ml
- bin/jsoo_common.mli
- bin/jsoo_main.ml
- nix/default.nix
I think the "vendored" definitions of `Unsafe`, `number_of_float` etc. were there for historical reasons, as it was hard to consume jsoo as a library. But that's not the case anymore.
> playground: use js_of_ocaml library

- bin/jsoo_common.ml
- bin/jsoo_main.ml
- test/blackbox-tests/playground.t
Showcases that when warnings are found, the error message passed in the json by the playground app is not good.
> playground: add test for bad error msg

- flake.lock
- jscomp/stdlib/float.cppo.ml
- jscomp/stdlib/float.cppo.mli
> [stdlib]: fix some Float functions

- jscomp/common/js_config.cppo.ml
Fixes #695.
I spent some time trying to write a test that would show the change, but I ended up realizing that `setup.sh` was ignoring `dom` already:
https://github.com/melange-re/melange/blob/539bfc00870c1d90150d6ffe7968c45b173943d6/test/blackbox-tests/setup.sh#L3
> stdlib paths: don't include `dom` by default

- jscomp/test/dune
- nix/default.nix
follow-up to https://github.com/melange-re/melange/pull/703
> fix(ci): add `melange.dom` to `libraries` in the runtime tests

- jscomp/core/js_dump.ml
- jscomp/core/js_packages_info.ml
- jscomp/core/js_pass_flatten.ml
- jscomp/core/js_pass_flatten_and_mark_dead.ml
- jscomp/core/lam_arity_analysis.ml
- jscomp/core/lam_compile.ml
- jscomp/core/lam_eta_conversion.ml
- jscomp/core/lam_print.ml
- jscomp/ext/ext_list.ml
- jscomp/ext/ext_list.mli
- jscomp/ext/ext_path.ml
- ppx/ast_attributes.ml
- ppx/ast_bs_open.ml
- ppx/ast_derive/ast_derive_abstract.ml
- ppx/ast_tuple_pattern_flatten.ml
- ppx/utf8_string.ml
- test/unit-tests/ounit_list_test.ml
this gets us a bit closer to removing `ext` from the melange-ppx, and making `ext` a private library again
> chore: remove some more Ext_list functions

- Changes.md
- jscomp/runtime/caml_sys.ml
- jscomp/runtime/caml_sys.mli
- test/blackbox-tests/sys-argv.t
It seems `Sys.argv` is behaving in a strange way, where the first value in the array is the command, and the second is another array with the actual args.
This is different to what `Node.Process.argv` is doing (which behaves in the expected way).
> test sys.argv

- Changes.md
- jscomp/runtime/js_internal.ml
- jscomp/test/hash_sugar_desugar.mli
- jscomp/test/mel_267_test.ml
- jscomp/test/re_or_res/reasonReactOptimizedCreateClass.re
- jscomp/test/unsafe_this.ml
- test/blackbox-tests/builtin-ppx-cmi-consistency.t
- test/blackbox-tests/mel-unwrap-for-obj.t
- test/blackbox-tests/melange-playground/compile-ml-obj.t
Looks like there's a missing commit from https://github.com/rescript-lang/rescript-compiler/pull/4967 that we must have forgotten to revert: https://github.com/rescript-lang/rescript-compiler/pull/4967/commits/ee283b0cb9fbea5132d8e77271f1f231d4fba4c5
I'm going to do another pass over the full PR and make sure we're not missing anything else.
fixes #758
> fix: make `Js.t` abstract (again)

- bin/dune
- bin/jsoo_main.ml
- bin/melc.ml
- bin/melc_cli.ml
- jscomp/core/dune
still a part of https://github.com/melange-re/melange/issues/113, perhaps the last one
> refactor: wrap `core` library, rename it to `melangelib`

- bin/dune
looks like it was added by mistake in https://github.com/melange-re/melange/pull/779 and I didn't catch it when reviewing, but this doesn't actually do anything, and would produce a dune error if used (it only has `modes melange`).
> fix(playground): remove `melange.dom` dependency from `bin/jsoo_main.bc.js`

- Changes.md
- jscomp/others/belt_Result.ml
- jscomp/others/belt_Result.mli
- jscomp/others/dune
- jscomp/stdlib/camlinternalOO.cppo.ml
- jscomp/stdlib/dune
- jscomp/stdlib/stdlib.cppo.ml
- jscomp/stdlib/stdlib.cppo.mli
- jscomp/test/dist/jscomp/test/ocaml_re_test.js
- jscomp/test/dune
- test/blackbox-tests/belt-and-runtime.t
- removes `melange.belt` as a dependency for the melange stdlib
- uses OCaml maps in the stdlib again
- a future PR will stop adding `melange.belt` to the libraries that melange auto-includes by default
> feat: remove `Belt` dependency from Stdlib

- jscomp/core/js_implementation.ml
this is not yet supported, so we shouldn't pretend to do any work
> refactor: stop calling `process_with_gentype` for now

- bin/jsoo_main.ml
- test/blackbox-tests/melange-playground/compile-re-error-syntax-locations.t
In #850 the public interface changed, from `js_error_msg` to `js_warning_error_msg`. But I forgot to update one place.
> Playground: fix warn error prop

- ppx/utf8_string.ml
- test/blackbox-tests/utf8-string-interp.t
- test/unit-tests/ounit_unicode_tests.ml
based on [feedback](https://github.com/melange-re/melange/pull/888#discussion_r1392126428) from #888
> fix: move utf8-string interpolation empty error back 1 char

- ppx/ast_attributes.ml
- ppx/ast_attributes.mli
- ppx/melange_ppx.ml
- test/blackbox-tests/export-invalid-names.t
also remove the found `@mel.as` attribute after processing
> feat(ppx): error on duplicate `@mel.as` attributes

- jscomp/core/lam.mli
- jscomp/melstd/array.mli
- jscomp/melstd/hash_set.mli
- jscomp/others/belt_Id.mli
- jscomp/others/belt_Range.mli
- jscomp/others/belt_Set.cppo.mli
- jscomp/others/sort.cppo.mli
- jscomp/runtime/js.ml
- jscomp/runtime/js_internal.ml
- jscomp/runtime/js_json.mli
- jscomp/runtime/js_promise.ml
- jscomp/runtime/js_re.ml
- jscomp/runtime/js_string.ml
- jscomp/runtime/js_undefined.mli
- jscomp/stdlib/stdlib.cppo.mli
Part of #693.
Still a long way to go, there are lots of other warnings in compiler libs, e.g.
```
File "vendor/melange-compiler-libs/lib/parse.mli", line 87, characters 29-43:
Warning: Failed to resolve reference unresolvedroot(Longident).t Couldn't find "Longident"
```
And also in melange itself, due to the way `Js_internal` is included I believe:
```
Warning, resolved hidden path: Js__.Js_internal.Fn.arity2
```
There are also other warnings that I have no clue how to solve about alerts, e.g.:
```
File "jscomp/stdlib/moreLabels.mli", line 63, character 2 to line 65, character 3:
Warning: Alert unsynchronized_access not expected here.
```
But this PR already includes some fixes, maybe can be considered to merge to keep doing progressive improvements.
> docs: remove warnings, part 1

- .github/workflows/opam-build.yml
- Changes.md
- Makefile
- flake.lock
- flake.nix
- nix/ci/test.nix
> feat: upgrade to the OCaml 5.1.1 branch

- ppx/ast_external_process.ml
- ppx/error.ml
- test/blackbox-tests/ffi-error-debug.t
- test/blackbox-tests/legacy-ounit-cmd.t
- test/blackbox-tests/ppx-errors.t
This is the last set of improvements to the error messages in `melange.ppx`.
The only set of messages remaining to improve are in the compiler core.
> fix(ppx): improve the last set of error messages in `melange.ppx`

- Changes.md
- jscomp/test/demo.ml
- jscomp/test/test_array_primitive.ml
- ppx/ast_external_process.ml
this change unifies the FFI language a bit more, disallowing `external` declarations with `[@@mel.new "Constructor"]`.
it plays better with the warnings that we issue when the external primitive name is `""`. In this case, the constructor must always appear in the primitive name, which makes the FFI language a bit more consistent.
> feat(ppx): disallow attribute payload in `[@mel.new]`

- Makefile
after #926, we need to set up a switch with ocaml-variants.5.1.1-trunk.
@jchavarri could you try setting up an opam switch for this new change and check if it works?
> chore(build): fix makefile for OCaml 5.1.1-trunk

- test/blackbox-tests/mel-uncurry-nesting.t
Adds a test to illustrate #752.
> add test for mel.uncurry

- jscomp/runtime/js_string.ml
- jscomp/test/dist/jscomp/test/js_string_test.js
- jscomp/test/js_string_test.ml
- Update some docs that were missed in #893 
- Fold `normalizeByForm` and `normalize` under a single function
> js_string: fixes + normalize

- melange.opam
- melange.opam.template
a small follow up to #962. there's a constraint on lsp server: `ocaml-lsp-server → merlin-lib < 5.0`. the changes in this pr work around it by replacing `dev` with `4.13.1-501` for merlin pkgs. for some reason these packages [have been already published](https://github.com/ocaml/opam-repository/pull/24882/), but they don't appear in the opam main mirror.
> opam: fix ocaml-lsp installation

- ppx/ast_derive/ast_derive_abstract.ml
After moving to ppxlib / deriving, the ppx doesn't generate an abstract type anymore. The old core type being created was just discarded by callers, this PR just cleans the related code.
No changes in any behavior should happen.
> Simplify derive abstract handling

- test/blackbox-tests/meth-arity.t
- partly extracted from #984
- showing a bad error related to `'a Js__Js_OO.Meth.arity2` which I'll fix in a separate PR (and should change the diff)
> test: show how to use `[@mel.meth]`

- Changes.md
- flake.lock
- test/blackbox-tests/meth-arity.t
- part of #983 
- companion to https://github.com/melange-re/melange-compiler-libs/pull/34
- messages previously displayed as `'a Js__Js_OO.Meth.arityN` are now `('a [@mel.meth])`
> fix: print better errors for mismatched [@mel.meth] arity

- Changes.md
- jscomp/runtime/js_re.ml
- jscomp/test/gpr_1501_test.ml
- jscomp/test/gpr_3895_test.ml
- jscomp/test/js_re_test.ml
Maybe it makes sense to add labeled args to `Js.Re` for consistency with `Js.String`, `Js.Array`...
cc @davesnx
> `Js.Re`: add labeled argument

- jscomp/core/js_dump_string.ml
- jscomp/core/js_dump_string.mli
- ppx/utf8_string.ml
This change is best viewed without whitespace https://github.com/melange-re/melange/pull/994/files?w=1
> fix(utf8): emit `Js.String` instead of `Js.String2`

- bin/melc.ml
- flake.lock
- flake.nix
- jscomp/core/ast_io.cppo.ml
- jscomp/core/ast_io.mli
- jscomp/core/dune
- jscomp/core/gen/record_fold.ml
- jscomp/core/gen/record_iter.ml
- jscomp/core/gen/record_map.ml
- jscomp/core/initialization.cppo.ml
- jscomp/core/lam_convert.cppo.ml
- jscomp/core/polyvar_pattern_match.cppo.ml
- playground/mel_playground.ml
This change adapts Melange to work with both the `master` and [`anmonteiro/414`](https://github.com/melange-re/melange-compiler-libs/tree/anmonteiro/414) branches over on [melange-compiler-libs](https://github.com/melange-re/melange-compiler-libs/).
The bulk of the work is done in `melange-compiler-libs`, which now has 2 typechecker versions.
> feat: allow melange to work with OCaml 4.14

- jscomp/core/ast_config.ml
- jscomp/core/record_attributes_check.ml
- ppx/ast_attributes.ml
- ppx/ast_attributes.mli
- ppx/ast_external_process.ml
- ppx/mel_ast_invariant.ml
- ppx/mel_ast_invariant.mli
- ppx/melange_ppx.ml
- test/blackbox-tests/mel-attributes.t
- this was brought up when migrating from v2 to v3.
- the fact that melange stopped warning about `bs.*` attributes means that some modules now produce errors at runtime if they have old code -- this is unacceptable.
- we now produce a hard error when finding a `bs.*` attribute
> feat: produce a hard error for `bs.*` attributes

- nix/default.nix
- nix/overlay.nix
since we started supporting multiple versions of OCaml in v3, some cram test output looks different between 4.14 and 5.1. It's not convenient to have them run by default in the overlay we distribute.
> nix: add missing dependency, don't run tests in the overlay

- README.md
Beginner here, this gave me some trouble installing melange following -
https://github.com/melange-re/melange?tab=readme-ov-file#installation
Might save 5 minutes for someone in the future
https://github.com/melange-re/melange/pull/926
> doc/fix: Add ocaml 5.1.1 as melange v3 dependency

- Changes.md
- jscomp/core/lam_arity_analysis.ml
- jscomp/core/lam_compile.ml
- jscomp/core/lam_compile_env.ml
- jscomp/core/lam_compile_env.mli
- jscomp/core/lam_pass_remove_alias.ml
- jscomp/core/mel_exception.mli
- test/blackbox-tests/virtual-lib-compilation.t
this is the melange part of the fix for #658. 
- Melange looks for some inlining information in the `.cmj` files for implementations. When compiling virtual libraries, `.cmj` files are deferred until a specific implementation has been selected, so they won't be available at this time
- There's a more thorough explanation in the code about what the fix does.
fixes #658 
TODO:
> fix: handle case of missing `.cmj` when trying to inline external field

- jscomp/runtime/js_set.ml
- jscomp/test/dist/jscomp/test/js_set_test.js
- jscomp/test/js_set_test.ml
Now that https://github.com/melange-re/melange/pull/1060 is merged, this one adds bindings to `entries` and `values` functions
> js_set: add values and entries

- Changes.md
- bin/melc.ml
- flake.lock
- jscomp/common/lam_constant.mli
- jscomp/common/lam_tag_info.mli
- jscomp/core/ast_config.mli
- jscomp/core/ast_io.cppo.ml
- jscomp/core/ast_io.mli
- jscomp/core/builtin_ast_mapper.ml
- jscomp/core/builtin_ast_mapper.mli
- jscomp/core/import.ml
- jscomp/core/js_implementation.mli
- jscomp/core/mel_ast_invariant.mli
- jscomp/core/meldep.mli
- jscomp/core/ml_binary.mli
- jscomp/core/pparse_driver.mli
- jscomp/core/record_attributes_check.ml
- playground/mel_playground.ml
- ppx/melange_ppx.ml
- test/blackbox-tests/virtual-lib-compilation.t
- vendor/dune
adapts melange to the newly slimmed down melange-compiler libs (afer https://github.com/melange-re/melange-compiler-libs/pull/40)
> adapt to slimmed-down melange-compiler-libs

- test/blackbox-tests/dune-virtual-library.t/dune
- test/blackbox-tests/dune-virtual-library.t/dune-project
- test/blackbox-tests/dune-virtual-library.t/impl_melange/dune
- test/blackbox-tests/dune-virtual-library.t/impl_melange/virt.ml
- test/blackbox-tests/dune-virtual-library.t/mel.ml
- test/blackbox-tests/dune-virtual-library.t/run.t
- test/blackbox-tests/dune-virtual-library.t/vlib/dune
- test/blackbox-tests/dune-virtual-library.t/vlib/virt.mli
- test/blackbox-tests/dune-virtual-library.t/vlib/vlib.ml
I suspect this will be useful as we enable a few more optimizations that depend on cmj files
> test: add a test exercising virtual libraries

- dune-project
- jscomp/core/lam_compile_main.cppo.ml
- jscomp/core/lam_pass_count.ml
- jscomp/core/lam_pass_count.mli
- jscomp/core/lam_pass_lets_dce.cppo.ml
- jscomp/core/lam_stats.ml
- jscomp/core/lam_stats.mli
- melange.opam
- nix/default.nix
- vendor/pp/LICENSE.md
- vendor/pp/dune
- vendor/pp/pp.ml
- vendor/pp/pp.mli
- I noticed a cycle when trying out the patched ppx_enumerate:
- melange -> pp -> ppx_expect (for tests) -> ppx_inline_test -> time_now -> ppx_base -> ppx_enumerate -> melange
- vendoring `pp` breaks the cycle by removing the dependency from melange to `pp`
> vendor `pp` to remove its dependency

- jscomp/runtime/expand_module_aliases.awk
- jscomp/runtime/js_array.ml
- jscomp/runtime/js_typed_array.cppo.ml
now that we have `Js.iterator`, we can re-enable these functions
> runtime: enable more iteration functions

- jscomp/core/melc_warnings.ml
- test/blackbox-tests/flags.t
this fixes a bug that was found when trying to update the melange version in the dune test suite
the root cause is that we slimmed down `melange-compiler-libs` quite a bit in https://github.com/melange-re/melange-compiler-libs/pull/40 because we're releasing melange versions specific to each compiler version.
As part of the above, we stopped tracking the OCaml parser and lexer, which also emit warnings. Therefore, we must set their warnings appropriately, too.
> fix: set warnings for upstream compiler libs too

- .github/workflows/nix-build.yml
gh actions moved macos-latest to arm64
> fix macos x86_64 github actions

- test/blackbox-tests/empty-obj.t
- this is related to https://github.com/reasonml/reason/issues/2387
- JS allows empty object keys, though, so I'm unsure whether we should allow this or not
> test: show crash with empty object key

- jscomp/others/dom.ml
This PR add type definition needed for web worker.
[Issue in melange-webapi](https://github.com/melange-community/melange-webapi/issues/18)
[Related PR in melange-webapi](https://github.com/melange-community/melange-webapi/pull/19)
> feat: add worker related doms

- jscomp/common/external_arg_spec.ml
- jscomp/common/external_arg_spec.mli
- jscomp/common/external_ffi_types.ml
- jscomp/common/external_ffi_types.mli
- jscomp/core/lam_compile_external_call.ml
- jscomp/core/lam_compile_external_call.mli
- jscomp/core/lam_compile_external_obj.ml
- jscomp/core/lam_compile_external_obj.mli
- jscomp/core/lam_ffi.ml
- jscomp/core/lam_ffi.mli
- jscomp/core/lam_primitive.ml
- jscomp/core/lam_primitive.mli
- ppx/ast_external_mk.ml
- ppx/ast_external_process.ml
part of the work towards https://github.com/melange-re/melange/issues/1159
> refactor: external arg spec ffi representation

- vendor/dune
the previous setup didn't work well with Merlin, likely because of all the `copy_files{,#}` stanzas. Using `include_subdirs qualified` allows us to get editor support in the vendored submodule.
> build: add Merlin support for melange-compiler-libs submodule

- nix/default.nix
it looks like we were building nodejs in tests for macos-13?
> chore(build): use nodejs_latest

- jscomp/common/external_arg_spec.ml
- jscomp/common/external_arg_spec.mli
- jscomp/common/external_ffi_types.ml
- jscomp/common/external_ffi_types.mli
- jscomp/core/js_cmj_format.ml
- jscomp/core/lam_analysis.ml
- jscomp/core/lam_compile_external_call.ml
- jscomp/core/lam_compile_external_call.mli
- jscomp/core/lam_compile_external_obj.ml
- jscomp/core/lam_compile_external_obj.mli
- jscomp/core/lam_ffi.ml
- jscomp/core/lam_ffi.mli
- jscomp/core/lam_primitive.ml
- jscomp/core/lam_primitive.mli
- jscomp/test/dist/jscomp/test/gpr_4442_test.js
- ppx/ast_derive/ast_derive_abstract.ml
- ppx/ast_external.ml
- ppx/ast_external_process.ml
- ppx/ast_external_process.mli
- ppx/ast_object.ml
part of a wider refactor to make the `external` FFI PPX code a bit easier to maintain
> refactor: external_arg_spec

- Changes.md
- jscomp/others/node_buffer.ml
> fix `Node.Buffer.fromString` signature, add all supported encodings

- Changes.md
- jscomp/runtime/js.pre.ml
- jscomp/runtime/js.pre.mli
- jscomp/runtime/js_typed_array.cppo.ml
pre-requisite to fix the build failures in #1218
> runtime: add `TypedArray` types at the toplevel in `Js`

- test/blackbox-tests/persistent-structure-error.t
Repro a bug that surfaced in https://github.com/melange-community/melange-json/pull/32/commits/c669c0790de9a3d80d8403d92fb60f11338362b2.
The `inner` lib represents `melange-json` lib, `outer` represents `melange-json.ppx` and the runtime.
The issue seems to happen due to a combination of two things:
- `outer` depends on `inner` but this is not reflected on the `ppx_runtime_libraries` 
- Usage of `(implicit_transitive_deps false)`, using `true` makes the issue go away
> Showcase error when using ppx runtime libs

- jscomp/runtime/js_array.ml
this is an example of `external` declaration that becomes way more readable after #1252
> runtime(js.array): port most `@mel.send.pipe` functions to `@mel.send`

- jscomp/runtime/js_blob.ml
- jscomp/runtime/js_file.ml
- jscomp/runtime/js_formData.ml
> runtime(Js.{FormData,Blob,File}): port @mel.send externals to use @mel.send

- jscomp/core/compile_letrec.520.ml
- jscomp/core/compile_rec_module.cppo.ml
Melange doesn't support the `Tupled` calling convention.
> fix: use `Lambda.lfunction'` with kind `Curried`

- jscomp/runtime/js.pre.ml
- jscomp/runtime/js.pre.mli
- jscomp/runtime/js_fetch.ml
The minimum required to share types from reason-react and melange-fetch
> Add Js.Fetch.{request,response,body,headers} as abstract

- Changes.md
- jscomp/core/lam_pass_remove_alias.ml
- jscomp/test/dist/jscomp/test/flow_parser_reg_test.js
- jscomp/test/dist/jscomp/test/ocaml_parsetree_test.js
- jscomp/test/dist/jscomp/test/ocaml_proto_test.js
- jscomp/test/dist/jscomp/test/ocaml_re_test.js
- jscomp/test/dist/jscomp/test/ocaml_typedtree_test.js
- jscomp/test/dist/jscomp/test/parser_api.js
- test/blackbox-tests/wrong-option-compilation.t
> fix: option nesting optimization bug

- test/blackbox-tests/ocaml-14200.t
this is the same as OCaml PR14200, demonstrated in Melange, and fixed in the upcoming OCaml 5.4 bump
> test: show bad variance check with private aliases
